name: MeatPad
options:
  bundleIdPrefix: com.thecoldzero
  deploymentTarget:
    macOS: "14.0"
packages:
  MeatPadKit:
    path: MeatPadKit
  STTextView:
    url: https://github.com/krzyzanowskim/STTextView
    exactVersion: 2.3.10
targets:
  MeatPad:
    type: application
    platform: macOS
    sources: [App]
    dependencies:
      - package: MeatPadKit
      - package: STTextView
        product: STTextView
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: MeatPad
        LSMinimumSystemVersion: "14.0"
        NSHumanReadableCopyright: "© 2026 Rokas"
    settings:
      base:
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_APP_SANDBOX: NO
        SWIFT_VERSION: "5.10"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
