// swift-tools-version:5.10
import PackageDescription

let package = Package(
    name: "MeatPadKit",
    platforms: [.macOS(.v14)],
    products: [.library(name: "MeatPadKit", targets: ["MeatPadKit"])],
    dependencies: [
        .package(url: "https://github.com/ChimeHQ/SwiftTreeSitter", from: "0.25.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-json", from: "0.24.8"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-typescript", from: "0.23.2"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-html", from: "0.23.2"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-ruby", from: "0.23.1"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-bash", from: "0.25.1"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-go", from: "0.25.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-rust", from: "0.24.2"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-c", from: "0.24.2"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-cpp", from: "0.23.4"),
        // Pinned to last release BEFORE the autogenerated conditional manifest
        // (`if FileManager.fileExists("src/scanner.c")`), which silently drops the
        // external scanner when the grammar is consumed as an SPM dependency (the
        // check runs against the wrong cwd), producing link errors. Newer tags are
        // unusable here until upstream fixes the manifest.
        .package(url: "https://github.com/tree-sitter/tree-sitter-javascript", exact: "0.23.1"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-css", exact: "0.23.2"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-python", exact: "0.23.6"),
        .package(url: "https://github.com/tree-sitter-grammars/tree-sitter-yaml", exact: "0.7.0"),
        .package(url: "https://github.com/tree-sitter-grammars/tree-sitter-markdown", exact: "0.5.3"),
        // Swift grammar has no checked-in generated parser on its release tags; the
        // `with-generated-files` branch ships them plus a working Package.swift.
        // Pinned to an immutable commit of that branch so `swift package update`
        // can't re-resolve it and a force-push/branch-delete can't break us.
        .package(url: "https://github.com/alex-pinkus/tree-sitter-swift", revision: "31d17fe7e818a2048c808b5c6fdc2dc792f4f5b5"),
    ],
    targets: [
        .target(
            name: "MeatPadKit",
            dependencies: [
                .product(name: "SwiftTreeSitter", package: "SwiftTreeSitter"),
                .product(name: "SwiftTreeSitterLayer", package: "SwiftTreeSitter"),
                .product(name: "TreeSitterJSON", package: "tree-sitter-json"),
                .product(name: "TreeSitterJavaScript", package: "tree-sitter-javascript"),
                // TreeSitterTypeScript product bundles both the TypeScript and TSX modules.
                .product(name: "TreeSitterTypeScript", package: "tree-sitter-typescript"),
                .product(name: "TreeSitterHTML", package: "tree-sitter-html"),
                .product(name: "TreeSitterCSS", package: "tree-sitter-css"),
                .product(name: "TreeSitterPython", package: "tree-sitter-python"),
                .product(name: "TreeSitterRuby", package: "tree-sitter-ruby"),
                .product(name: "TreeSitterBash", package: "tree-sitter-bash"),
                .product(name: "TreeSitterGo", package: "tree-sitter-go"),
                .product(name: "TreeSitterRust", package: "tree-sitter-rust"),
                .product(name: "TreeSitterC", package: "tree-sitter-c"),
                .product(name: "TreeSitterCPP", package: "tree-sitter-cpp"),
                .product(name: "TreeSitterYAML", package: "tree-sitter-yaml"),
                .product(name: "TreeSitterSwift", package: "tree-sitter-swift"),
                // TreeSitterMarkdown product bundles both the block and inline modules.
                .product(name: "TreeSitterMarkdown", package: "tree-sitter-markdown"),
            ]
        ),
        .testTarget(name: "MeatPadKitTests", dependencies: ["MeatPadKit"]),
    ]
)
